### ISSUE TITLE
Error to install vmod libvmod-gossip on varnish 5

### ISSUE THREAD

**Issue by thiagomengue** [carlosabalde/libvmod-gossip#1]
Hello,

I'm try to install the version 4.1, but the following error occurs:

Version of OS and varnish:
varnish-5.2.1 revision 67e562482
Ubuntu 18.04.1 LTS

I tried too to install the version of master, but without success.

Output:

root@6e43dfb8e3d7:/varnish-vmod-gossip-4.1-1.0# make
make  all-recursive
make[1]: Entering directory '/varnish-vmod-gossip-4.1-1.0'
Making all in src
make[2]: Entering directory '/varnish-vmod-gossip-4.1-1.0/src'
/usr/share/varnish/vmodtool.py ../src/vmod_gossip.vcc
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/varnish -Wall -Werror   -g -O2 -MT vmod_gossip.lo -MD -MP -MF .deps/vmod_gossip.Tpo -c -o vmod_gossip.lo vmod_gossip.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/varnish -Wall -Werror -g -O2 -MT vmod_gossip.lo -MD -MP -MF .deps/vmod_gossip.Tpo -c vmod_gossip.c  -fPIC -DPIC -o .libs/vmod_gossip.o
vmod_gossip.c:217:55: error: 'enum exp_event_e' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 callback(struct worker *wrk, struct objcore *oc, enum exp_event_e e, void *priv)
                                                       ^~~~~~~~~~~
vmod_gossip.c:217:67: error: parameter 3 ('e') has incomplete type
 callback(struct worker *wrk, struct objcore *oc, enum exp_event_e e, void *priv)
                                                                   ^
vmod_gossip.c: In function 'callback':
vmod_gossip.c:224:14: error: 'EXP_INSERT' undeclared (first use in this function); did you mean 'VRB_INSERT'?
         case EXP_INSERT:
              ^~~~~~~~~~
              VRB_INSERT
vmod_gossip.c:224:14: note: each undeclared identifier is reported only once for each function it appears in
vmod_gossip.c:225:14: error: 'EXP_INJECT' undeclared (first use in this function); did you mean 'EXP_INSERT'?
         case EXP_INJECT:
              ^~~~~~~~~~
              EXP_INSERT
vmod_gossip.c:229:14: error: 'EXP_REMOVE' undeclared (first use in this function); did you mean 'VRB_REMOVE'?
         case EXP_REMOVE:
              ^~~~~~~~~~
              VRB_REMOVE
In file included from /usr/include/varnish/common/common.h:41:0,
                 from /usr/include/varnish/cache/cache.h:39,
                 from vmod_gossip.c:10:
vmod_gossip.c: In function 'dump':
vmod_gossip.c:283:34: error: 'struct objcore' has no member named 'exp'; did you mean 'keep'?
                     (object->oc->exp.t_origin + object->oc->exp.ttl) - now));
                                  ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_gossip.c:282:17: note: in expansion of macro 'AZ'
                 AZ(VSB_printf(vsb, "\"ttl\":%.6f,",
                 ^~
vmod_gossip.c:283:61: error: 'struct objcore' has no member named 'exp'; did you mean 'keep'?
                     (object->oc->exp.t_origin + object->oc->exp.ttl) - now));
                                                             ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_gossip.c:282:17: note: in expansion of macro 'AZ'
                 AZ(VSB_printf(vsb, "\"ttl\":%.6f,",
                 ^~
vmod_gossip.c:284:67: error: 'struct objcore' has no member named 'exp'; did you mean 'keep'?
                 AZ(VSB_printf(vsb, "\"grace\":%.6f,", object->oc->exp.grace));
                                                                   ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_gossip.c:284:17: note: in expansion of macro 'AZ'
                 AZ(VSB_printf(vsb, "\"grace\":%.6f,", object->oc->exp.grace));
                 ^~
vmod_gossip.c:285:65: error: 'struct objcore' has no member named 'exp'; did you mean 'keep'?
                 AZ(VSB_printf(vsb, "\"keep\":%.6f", object->oc->exp.keep));
                                                                 ^
/usr/include/varnish/vas.h:59:8: note: in definition of macro 'assert'
  if (!(e)) {       \
        ^
vmod_gossip.c:285:17: note: in expansion of macro 'AZ'
                 AZ(VSB_printf(vsb, "\"keep\":%.6f", object->oc->exp.keep));
                 ^~
vmod_gossip.c: In function 'event_function':
vmod_gossip.c:567:35: error: implicit declaration of function 'EXP_Register_Callback' [-Werror=implicit-function-declaration]
                 callback_handle = EXP_Register_Callback(
                                   ^~~~~~~~~~~~~~~~~~~~~
vmod_gossip.c:581:17: error: implicit declaration of function 'EXP_Deregister_Callback' [-Werror=implicit-function-declaration]
                 EXP_Deregister_Callback(&callback_handle);
                 ^~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:462: recipe for target 'vmod_gossip.lo' failed
make[2]: *** [vmod_gossip.lo] Error 1
make[2]: Leaving directory '/varnish-vmod-gossip-4.1-1.0/src'
Makefile:517: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/varnish-vmod-gossip-4.1-1.0'
Makefile:385: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by carlosabalde** [comment]
There is a branch in the repo for each major Varnish version, but support for 5.0, 5.1 and 5.2 was never implemented. Sorry.
